// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Packet_ErrCode.proto

#ifndef PROTOBUF_Packet_5fErrCode_2eproto__INCLUDED
#define PROTOBUF_Packet_5fErrCode_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_enum_reflection.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_Packet_5fErrCode_2eproto();
void protobuf_AssignDesc_Packet_5fErrCode_2eproto();
void protobuf_ShutdownFile_Packet_5fErrCode_2eproto();


enum ErrCode {
  Error_OK = 0,
  Error_Unknow = 1,
  Error_Account = 2,
  Error_Pwd = 3,
  Error_sys_mysql = 4,
  Error_registerAccount = 5,
  Error_LoginGameSessionKey = 6,
  Error_LoginGameAccountId = 7
};
bool ErrCode_IsValid(int value);
const ErrCode ErrCode_MIN = Error_OK;
const ErrCode ErrCode_MAX = Error_LoginGameAccountId;
const int ErrCode_ARRAYSIZE = ErrCode_MAX + 1;

const ::google::protobuf::EnumDescriptor* ErrCode_descriptor();
inline const ::std::string& ErrCode_Name(ErrCode value) {
  return ::google::protobuf::internal::NameOfEnum(
    ErrCode_descriptor(), value);
}
inline bool ErrCode_Parse(
    const ::std::string& name, ErrCode* value) {
  return ::google::protobuf::internal::ParseNamedEnum<ErrCode>(
    ErrCode_descriptor(), name, value);
}
// ===================================================================


// ===================================================================


// ===================================================================


// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {

template <>
inline const EnumDescriptor* GetEnumDescriptor< ::ErrCode>() {
  return ::ErrCode_descriptor();
}

}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_Packet_5fErrCode_2eproto__INCLUDED
