// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Packet_ErrCode.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "Packet_ErrCode.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace {

const ::google::protobuf::EnumDescriptor* ErrCode_descriptor_ = NULL;

}  // namespace


void protobuf_AssignDesc_Packet_5fErrCode_2eproto() {
  protobuf_AddDesc_Packet_5fErrCode_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "Packet_ErrCode.proto");
  GOOGLE_CHECK(file != NULL);
  ErrCode_descriptor_ = file->enum_type(0);
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_Packet_5fErrCode_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
}

}  // namespace

void protobuf_ShutdownFile_Packet_5fErrCode_2eproto() {
}

void protobuf_AddDesc_Packet_5fErrCode_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\024Packet_ErrCode.proto*\270\001\n\007ErrCode\022\014\n\010Er"
    "ror_OK\020\000\022\020\n\014Error_Unknow\020\001\022\021\n\rError_Acco"
    "unt\020\002\022\r\n\tError_Pwd\020\003\022\023\n\017Error_sys_mysql\020"
    "\004\022\031\n\025Error_registerAccount\020\005\022\035\n\031Error_Lo"
    "ginGameSessionKey\020\006\022\034\n\030Error_LoginGameAc"
    "countId\020\007", 209);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "Packet_ErrCode.proto", &protobuf_RegisterTypes);
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_Packet_5fErrCode_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_Packet_5fErrCode_2eproto {
  StaticDescriptorInitializer_Packet_5fErrCode_2eproto() {
    protobuf_AddDesc_Packet_5fErrCode_2eproto();
  }
} static_descriptor_initializer_Packet_5fErrCode_2eproto_;
const ::google::protobuf::EnumDescriptor* ErrCode_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return ErrCode_descriptor_;
}
bool ErrCode_IsValid(int value) {
  switch(value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
    case 6:
    case 7:
      return true;
    default:
      return false;
  }
}


// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)
